export const Educations = [
  {
    Studies: "B.E",
    title: " Computer Science and Engineering",
    at: "AAA College Of Engineering and Technology, Sivakasi",
    duration: "Jun 2019 - Mar 2023",
    desc: ["CGPA Scored - 8.02", "Percentage - 80%"],
  },
  {
    Studies: "12th Grade",
    title: " Higher Secondary Certificate",
    at: "MNMSPS Hr Sec School, Mallanginar",
    duration: "Jun 2017 - Apr 2019",
    desc: ["Marks Scored - 476/600", "Percentage - 78%"],
  },
  {
    Studies: "10th Grade",
    title: "Secondary School Certificate ",
    at: "MNMSPS Hr Sec School, Mallanginar",
    duration: "Jun 2016 - Mar 2017",
    desc: [" Marks Scored - 476/600", "Percentage - 95.2%"],
  },
  {
    Studies: "Other Courses",
    desc: [
      "FULL STACK WEB DEVELOPMENT BOOTCAMP (MERN)",
      "UI/UX DESIGN AND WEB & MOBILE DESIGNER COURSE",
      "AWS CLOUD ARCHITECTING COURSE (12725)",
    ],
  },
];

export const Certifications = [
  {
    title: "Full Stack Web Development Course Certificate (MERN)",
    Skills: [
      "Html5",
      "css",
      "js",
      "React",
      "redux",
      "Nodejs",
      "MongoDB",
      "ExpressJs",
    ],
    Duration: "Mar 2022 - Sep 2022",
    Img: require("../assets/Certifications/FullStackDev.jpg"),
    link: "http://ude.my/UC-da397f1d-1482-459b-a3fd-009a605d1da6",
  },
  {
    title: "Ui/Ux Design and Web & Mobile Designer Course certificate",
    Skills: [
      "Interaction design principles",
      "Branding, typography and color theory",
      "Wireframing and prototyping",
      "User research and personas",
      "Teamwork and communication skills",
      "Key industry tools, including Sketch",
    ],
    Duration: "sep 2022 - Dec 2022",
    Img: require("../assets/Certifications/UiCert.jpg"),
    link: "http://ude.my/UC-9213ce85-43fb-40b0-a3f1-2b4076a9cfbe",
  },
  {
    title: "AWS Cloud Architecting Course Certificate (12725)",
    Skills: [
      "EC-2 Instance",
      "Auto-Scaling",
      "Load Balancing",
      "EBS (Elastic Block Storage)",
      "Onject Storages in Cloud",
      "Route53",
      "Amazon virtual private Cloud (VPC)",
      "Relational Database Services (RDS)",
    ],
    Duration: "Apr 2022 - Aug 2022",
    Img: require("../assets/Certifications/aws.jpg"),
    link: "https://www.credly.com/badges/7980369f-f422-4c61-9072-dc427be32f97/public_url",
  },
  {
    title:
      "Google Map Clone Project Using ReactJs Virtual WorkShop certificate",
    Skills: [
      "React Components",
      "State in React",
      "React Props and PropTypes",
      "React Hooks",
      "Virtual Dom",
      "Expressions in JSX",
    ],
    Duration: " OneDay - 27th Aug 2022",
    Img: require("../assets/Certifications/GoogleMapWorkshop.jpg"),
    link: "https://drive.google.com/file/d/1DmFAMIlW0RRkdkbmB-W3v9VORRrmLdG_/view?usp=drivesdk",
  },
  {
    title: "NetFlix Clone Using Reactjs",
    Skills: [
      "React Components",
      "State in React",
      "React Props and PropTypes",
      "React Hooks",
      "Virtual Dom",
      "Expressions in JSX",
      "API Management",
    ],
    Duration: " 14 Nov 2022 - 19 Nov 2022",
    Img: require("../assets/Certifications/NetFlixClone.jpg"),
    link: "https://drive.google.com/file/d/1Ba2Bl-nwW1pEahKs8_kYSZbh9AZWrFrW/view?usp=drivesdk",
  },
  {
    title: "HTML & CSS Essentials Bootcamp",
    Skills: [
      "Basic HTML Concepts",
      "Advanced HTML Concepts",
      "Basic CSS Concepts",
      "Advanced CSS Concepts",
    ],
    Duration: " 29 Aug 2022 - 2 Sep 2022",
    Img: require("../assets/Certifications/html&css.jpg"),
    link: "https://drive.google.com/file/d/1Zy_5UpcphTeEoLFScv7xtNIvb_m2gsTS/view?usp=drivesdk",
  },
  {
    title: "JavaScript Programming Essentials Bootcamp",
    Skills: ["Basic Javascript Concepts", "Advanced Javascript Concepts"],
    Duration: " 5 Sep 2022 - 9 Sep 2022",
    Img: require("../assets/Certifications/js.jpg"),
    link: "https://drive.google.com/file/d/17LIDz_V4azGPYbnu2OYPK-CSiZH-9pZ5/view?usp=drivesdk",
  },
  {
    title: "javaScript & ReactJs Essentials Bootcamp",
    Skills: [
      "Basic JavaScript Concepts",
      "Advanced JavaScript Concepts",
      "Basic ReactJs Concepts",
      "Advanced ReactJs Concepts",
    ],
    Duration: " 12 sep 2022 - 16 Sep 2022",
    Img: require("../assets/Certifications/js&react.jpg"),
    link: "https://drive.google.com/file/d/1bGbpwqPJhyFIrn9eXyOnJ1Yru6cn53wE/view?usp=drivesdk",
  },
  {
    title: "javaScript & NodeJs Essentials Bootcamp",
    Skills: [
      "Basic JavaScript Concepts",
      "Advanced JavaScript Concepts",
      "Basic NodeJs Concepts",
      "Advanced NodeJs Concepts",
    ],
    Duration: " 23 Aug 2022 - 27 Aug 2022",
    Img: require("../assets/Certifications/js&node.jpg"),
    link: "https://drive.google.com/file/d/1JwbXyKSbP8_XQqjYN7ItBYwG62KZveHY/view?usp=drivesdk",
  },
];

export const ProjectShowcase = [
  {
    img: require("../assets/Projects/moonflix.png"),
    name: "MoonFlix App",
    link: "/Moonflix",
    technologies: [
      "MeterialUI",
      "SwiperJs",
      "ReactJs",
      "ExpressJs",
      "Mongoose",
    ],
    feautures: [
      "SignIn / SigunUp / Reset password",
      "Add / Remove movie to Favourite List",
      "write / Delete review for movie",
      "light / Dark theme",
    ],
    git: "https://github.com/Karthiksk123/Moonflix-App",
    site: "https://moonflix-app.vercel.app/",
  },
  {
    img: require("../assets/Projects/expense.png"),
    name: "Expense tracker App",
    link: "/Expense-Tracker-App",
    technologies: [
      "Html",
      "Css",
      "JS",
      "ReactJs",
      "ExpressJs",
      "Mongoose",
      "ChartJs",
    ],
    feautures: [
      "Track Expense of activities",
      "Fetch data from the backend",
      "add / delete activities",
      "chart recognized data UI",
    ],
    git: "https://github.com/Karthiksk123/Expense-Tracker-app",
    site: "https://expense-tracker-app-karthiksk123.vercel.app/",
  },
  {
    img: require("../assets/Projects/Starflix.png"),
    name: "StarFlix App",
    link: "/StarFlix-App",
    technologies: ["Html", "Css", "JS", "ReactJs", "ExpresJs", "Mongoose"],
    feautures: [
      "Search movie / tv series / peoples ",
      "Save movie to Favourite list",
      "Trailer features available",
      "Movie Suggestions",
    ],
    git: "https://github.com/Karthiksk123/StarFlix-App",
    site: "https://starflix-app.netlify.app/",
  },
];
